import {
	Activity,
	Ambulance,
	Apple,
	Baby,
	Bone,
	Brain,
	Briefcase,
	Bug,
	Cross,
	Dna,
	Droplet,
	Droplets,
	Ear,
	Eye,
	Filter,
	Flower2,
	Heart,
	HeartPulse,
	Leaf,
	type LucideIcon,
	Microscope,
	Radiation,
	Ribbon,
	Scale,
	ScanFace,
	Scissors,
	Search,
	Smile,
	Sparkles,
	Stethoscope,
	Syringe,
	TestTubes,
	User,
	Users,
	UtensilsCrossed,
} from "lucide-react";

export enum MedicalSpecialty {
	ALERGOLOGIA = "Alergologia",
	ANESTESIOLOGIA = "Anestesiologia",
	ANGIOLOGIA = "Angiologia",
	CANCEROLOGIA = "Cancerologia",
	CARDIOLOGIA = "Cardiologia",
	CIRURGIA_CARDIOVASCULAR = "Cirurgia Cardiovascular",
	CIRURGIA_CABECA_PESCOCO = "Cirurgia de Cabeça e Pescoço",
	CIRURGIA_DIGESTIVA = "Cirurgia do Aparelho Digestivo",
	CIRURGIA_GERAL = "Cirurgia Geral",
	CIRURGIA_PEDIATRICA = "Cirurgia Pediátrica",
	CIRURGIA_PLASTICA = "Cirurgia Plástica",
	CIRURGIA_TORACICA = "Cirurgia Torácica",
	CIRURGIA_VASCULAR = "Cirurgia Vascular",
	CLINICA_MEDICA = "Clínica Médica",
	DERMATOLOGIA = "Dermatologia",
	ENDOCRINOLOGIA = "Endocrinologia e Metabologia",
	ENDOSCOPIA = "Endoscopia",
	GASTROENTEROLOGIA = "Gastroenterologia",
	GERIATRIA = "Geriatria",
	GINECOLOGIA_OBSTETRICIA = "Ginecologia e Obstetrícia",
	HEMATOLOGIA = "Hematologia e Hemoterapia",
	HEPATOLOGIA = "Hepatologia",
	HOMEOPATIA = "Homeopatia",
	INFECTOLOGIA = "Infectologia",
	MASTOLOGIA = "Mastologia",
	MEDICINA_DE_EMERGENCIA = "Medicina de Emergência",
	MEDICINA_DO_ESPORTO = "Medicina do Esporte",
	MEDICINA_DO_TRABALHO = "Medicina do Trabalho",
	MEDICINA_DE_FAMILIA = "Medicina de Família e Comunidade",
	MEDICINA_FISICA_REABILITACAO = "Medicina Física e Reabilitação",
	MEDICINA_INTENSIVA = "Medicina Intensiva",
	MEDICINA_LEGAL = "Medicina Legal e Perícia Médica",
	NEFROLOGIA = "Nefrologia",
	NEUROCIRURGIA = "Neurocirurgia",
	NEUROLOGIA = "Neurologia",
	NUTROLOGIA = "Nutrologia",
	OFTALMOLOGIA = "Oftalmologia",
	ONCOLOGIA_CLINICA = "Oncologia Clínica",
	ORTOPEDIA_TRAUMATOLOGIA = "Ortopedia e Traumatologia",
	OTORRINOLARINGOLOGIA = "Otorrinolaringologia",
	PATOLOGIA = "Patologia",
	PATOLOGIA_CLINICA = "Patologia Clínica/Medicina Laboratorial",
	PEDIATRIA = "Pediatria",
	PNEUMOLOGIA = "Pneumologia",
	PSIQUIATRIA = "Psiquiatria",
	RADIOLOGIA = "Radiologia e Diagnóstico por Imagem",
	RADIOTERAPIA = "Radioterapia",
	REUMATOLOGIA = "Reumatologia",
	UROLOGIA = "Urologia",
}

// Dicionário mapeando a especialidade ao seu respectivo ícone
export const specialtyIcons: Record<MedicalSpecialty, LucideIcon> = {
	[MedicalSpecialty.ALERGOLOGIA]: Flower2,
	[MedicalSpecialty.ANESTESIOLOGIA]: Syringe,
	[MedicalSpecialty.ANGIOLOGIA]: Droplet,
	[MedicalSpecialty.CANCEROLOGIA]: Ribbon,
	[MedicalSpecialty.CARDIOLOGIA]: Heart,
	[MedicalSpecialty.CIRURGIA_CARDIOVASCULAR]: HeartPulse,
	[MedicalSpecialty.CIRURGIA_CABECA_PESCOCO]: User,
	[MedicalSpecialty.CIRURGIA_DIGESTIVA]: UtensilsCrossed,
	[MedicalSpecialty.CIRURGIA_GERAL]: Scissors,
	[MedicalSpecialty.CIRURGIA_PEDIATRICA]: Baby,
	[MedicalSpecialty.CIRURGIA_PLASTICA]: Sparkles,
	[MedicalSpecialty.CIRURGIA_TORACICA]: Heart,
	[MedicalSpecialty.CIRURGIA_VASCULAR]: Droplet,
	[MedicalSpecialty.CLINICA_MEDICA]: Stethoscope,
	[MedicalSpecialty.DERMATOLOGIA]: ScanFace,
	[MedicalSpecialty.ENDOCRINOLOGIA]: Dna,
	[MedicalSpecialty.ENDOSCOPIA]: Search,
	[MedicalSpecialty.GASTROENTEROLOGIA]: Apple,
	[MedicalSpecialty.GERIATRIA]: User,
	[MedicalSpecialty.GINECOLOGIA_OBSTETRICIA]: Baby,
	[MedicalSpecialty.HEMATOLOGIA]: Droplet,
	[MedicalSpecialty.HEPATOLOGIA]: Activity,
	[MedicalSpecialty.HOMEOPATIA]: Leaf,
	[MedicalSpecialty.INFECTOLOGIA]: Bug,
	[MedicalSpecialty.MASTOLOGIA]: Ribbon,
	[MedicalSpecialty.MEDICINA_DE_EMERGENCIA]: Ambulance,
	[MedicalSpecialty.MEDICINA_DO_ESPORTO]: Activity,
	[MedicalSpecialty.MEDICINA_DO_TRABALHO]: Briefcase,
	[MedicalSpecialty.MEDICINA_DE_FAMILIA]: Users,
	[MedicalSpecialty.MEDICINA_FISICA_REABILITACAO]: Cross,
	[MedicalSpecialty.MEDICINA_INTENSIVA]: Activity,
	[MedicalSpecialty.MEDICINA_LEGAL]: Scale,
	[MedicalSpecialty.NEFROLOGIA]: Filter,
	[MedicalSpecialty.NEUROCIRURGIA]: Brain,
	[MedicalSpecialty.NEUROLOGIA]: Brain,
	[MedicalSpecialty.NUTROLOGIA]: Apple,
	[MedicalSpecialty.OFTALMOLOGIA]: Eye,
	[MedicalSpecialty.ONCOLOGIA_CLINICA]: Ribbon,
	[MedicalSpecialty.ORTOPEDIA_TRAUMATOLOGIA]: Bone,
	[MedicalSpecialty.OTORRINOLARINGOLOGIA]: Ear,
	[MedicalSpecialty.PATOLOGIA]: Microscope,
	[MedicalSpecialty.PATOLOGIA_CLINICA]: TestTubes,
	[MedicalSpecialty.PEDIATRIA]: Baby,
	[MedicalSpecialty.PNEUMOLOGIA]: Heart,
	[MedicalSpecialty.PSIQUIATRIA]: Smile,
	[MedicalSpecialty.RADIOLOGIA]: Radiation,
	[MedicalSpecialty.RADIOTERAPIA]: Radiation,
	[MedicalSpecialty.REUMATOLOGIA]: Bone,
	[MedicalSpecialty.UROLOGIA]: Droplets,
};

// Exporta o array pronto para uso em Selects, Tables ou Listas
export const medicalSpecialties = Object.entries(MedicalSpecialty).map(
	([key, value]) => {
		const specialtyValue =
			MedicalSpecialty[key as keyof typeof MedicalSpecialty];
		return {
			value: specialtyValue,
			label: value,
			icon: specialtyIcons[specialtyValue],
		};
	},
);
